# Generated by Django 4.1.2 on 2022-10-25 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100, verbose_name='Referencia')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('procesador', models.CharField(max_length=100, verbose_name='Procesador')),
                ('memoria', models.CharField(max_length=100, verbose_name='Memoria')),
                ('disco', models.CharField(max_length=100, verbose_name='Disco')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='EquipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo Usuario',
                'verbose_name_plural': 'Equipos Usuarios',
            },
        ),
    ]
